# Generated by Django 5.0.4 on 2024-05-10 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myCV', '0007_alter_experience_end_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ('id',), 'verbose_name': 'Experience', 'verbose_name_plural': 'Experiences'},
        ),
    ]
