# Generated by Django 5.0.4 on 2024-05-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCV', '0010_remove_experience_company_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('start_year', models.IntegerField(verbose_name='Start Year')),
                ('end_year', models.IntegerField(blank=True, default=None, null=True, verbose_name='End Year')),
                ('faculty', models.CharField(blank=True, default='', max_length=254, verbose_name='Faculty')),
                ('school_location', models.CharField(blank=True, default='', max_length=254, verbose_name='School Location')),
                ('education_description', models.CharField(blank=True, default='', max_length=254, verbose_name='Education Description')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Education',
                'ordering': ('id',),
            },
        ),
    ]
